on:
  push:
    tags:
      - "v\\d+\\.\\d+\\.\\d+"
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Debug /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Debug /p:Version=${VERSION} --no-build

    - name: Pack 
      run: |
        dotnet pack --configuration Debug /p:Version=${VERSION} --no-build --output . Sanchez.DansUI.Icons
        dotnet pack --configuration Debug /p:Version=${VERSION} --no-build --output . Sanchez.DansUI

    - name: Push
      run: |
        dotnet nuget push Sanchez.DansUI.Icons.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        dotnet nuget push Sanchez.DansUI.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}